---
# GitHub Actions workflow for commits pushed to the Minie repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java8-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java11-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: 'build/reports/tests/test/index.html'

  Java11-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - run: ./gradlew build -Pbtdebug -Ppdb64 --console=plain --no-daemon --stacktrace
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java21-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java21-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - run: ./gradlew build -Pbtdebug --console=plain --no-daemon --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: 'build/reports/tests/test/index.html'

  Java21-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - run: ./gradlew build -Pbtdebug -Ppdb64 --console=plain --no-daemon --stacktrace
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'
