---
# GitHub Actions workflow for commits pushed to the Minie repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java17-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v5
      - run: ./gradlew build javadoc install -Pbtdebug --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java17-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v5
      - run: ./gradlew build javadoc install -Pbtdebug -Ppdb64 --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java21-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-13
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v5
      - run: ./gradlew build javadoc install -Pbtdebug --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java25-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 25
      - uses: actions/checkout@v5
      - run: ./gradlew build javadoc install -Pbtdebug --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java25-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-15
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 25
      - uses: actions/checkout@v5
      - run: ./gradlew build javadoc install -Pbtdebug --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: 'build/reports/tests/test/index.html'

  Java25-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2025
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 25
      - uses: actions/checkout@v5
      - run: ./gradlew build javadoc install -Pbtdebug -Ppdb64 --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'
