---
# GitHub Actions workflow for commits pushed to the Minie repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java8-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: actions/checkout@v4
      - run: ./gradlew build javadoc -Pbtdebug --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew build javadoc -Pbtdebug --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java11-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2019
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/checkout@v4
      - run: ./gradlew build javadoc -Pbtdebug -Ppdb64 --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-13
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v4
      - run: ./gradlew build javadoc -Pbtdebug --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java21-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - run: ./gradlew build javadoc -Pbtdebug --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'

  Java21-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-14
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
      - run: ./gradlew build javadoc -Pbtdebug --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: 'build/reports/tests/test/index.html'

  Java22-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 22
      - uses: actions/checkout@v4
      - run: ./gradlew build javadoc -Pbtdebug -Ppdb64 --console=plain --exclude-task :Jme3Examples:javadoc --stacktrace
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: 'MinieLibrary/*.log'
